<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur5_gripper_description</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="chenjuotung@gmail.com">justin</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>robotiq_description</depend>
  <depend>urdf</depend>
  <depend>xacro</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  
  <!-- Gazebo Sim (Harmonic) dependencies -->
  <exec_depend>ros_gzharmonic_sim</exec_depend>
  <exec_depend>ros_gzharmonic_bridge</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend>
  
  <!-- ros2_control dependencies -->
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>position_controllers</exec_depend>
  <exec_depend>ros2_controllers</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
