controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    use_sim_time: False

    joint_state_broadcaster.type: joint_state_broadcaster/JointStateBroadcaster

    platform_velocity_controller.type: "mecanum_drive_controller/MecanumDriveController"

platform_velocity_controller:
  ros__parameters:
    use_sim_time: False
    interface_name: velocity

    command_joint_names: ["front_left_wheel_joint", "rear_left_wheel_joint", "rear_right_wheel_joint", "front_right_wheel_joint"]

    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"

    kinematics.base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
    kinematics.wheels_radius: 0.05
    kinematics.sum_of_robot_center_projection_on_X_Y_axis: 0.4704
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0

    publish_rate: 20.0
    reference_timeout: 0.1
    use_stamped_vel: False

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

    cmd_vel_timeout: 0.5

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: false
    tf_frame_prefix_enable: false

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.max_velocity: 1.3
    linear.x.min_velocity: -1.3
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    linear.y.max_velocity: 1.3
    linear.y.min_velocity: -1.3
    linear.y.max_acceleration: 1.0
    linear.y.min_acceleration: -1.0
    linear.y.max_jerk: .NAN
    linear.y.min_jerk: .NAN

    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN

puma_control:
  ros__parameters:
    canbus_dev: 'vcan0'
    joint_names: ['front_left_wheel_joint', 'front_right_wheel_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint']
    joint_can_ids: [2, 3, 4, 5]
    joint_directions: [1, -1, 1, -1]
    gear_ratio: 24.0
    encoder_cpr: 10
    gain:
      p: 0.025
      i: 0.005
      d: 0.0
