#!/usr/bin/env python3
"""Generate the dirt and the cat map of the vacuum cleaner party house.

Slices the collision meshes of house_int2 (walls + furniture) at the robot
height to find the floor the vacuum can actually clean, then writes:
  pieces.txt        confetti and spilled paint for the vacuum_dirt system
  cat_map.pgm       area the cat walks on (dark = free) for cat_walker
  ../paint_can_*/   one knocked over paint can model per color

Development tool only, needs trimesh, pycollada, scipy and pillow:
  python3 generate_party_house.py <custom_robots_dir> <output_dir>
"""

import math
import re
import sys
from pathlib import Path

import numpy as np
import trimesh
from PIL import Image, ImageDraw
from scipy import ndimage

RES = 0.01
X0, X1, Y0, Y1 = -4.3, 5.7, -3.9, 6.3
ROBOT_RADIUS = 0.18
ROBOT_HEIGHT = 0.08
ROBOT_START = (-1.0, 1.5)
CAT_CLEARANCE = 0.08
CAT_MAP_RES = 0.05
SEED = 7

# Knocked over paint cans spread over the house (name, palette index, can
# center, puddle center where the cat steps). The can lies with its open end
# towards the puddle.
PAINTS = [
    ("red", 24, (1.27, 5.72), (0.92, 5.38)),
    ("blue", 26, (5.08, 1.10), (4.62, 1.34)),
    ("green", 28, (-3.72, -0.80), (-3.30, -0.55)),
    ("yellow", 30, (5.05, -1.10), (4.66, -1.42)),
]
CAN_RADIUS = 0.085
CAN_LENGTH = 0.17
CAN_FOOTPRINT = 0.16
PUDDLE_DROPS = 70

# Where the party was (x, y, sigma, weight)
HOTSPOTS = [(-0.8, 3.9, 1.3, 10.0), (-2.4, 0.3, 1.0, 5.0), (0.8, 2.0, 1.5, 2.0)]
BASE_DENSITY = 0.6
CONFETTI = 18000

# Palette indexes of vacuum_dirt.cpp: 8 colors x 3 shades, then the paints
# in 2 shades each
N_COLORS, N_SHADES = 8, 3
PAINT_RGB = {"red": (0.80, 0.10, 0.10), "blue": (0.10, 0.28, 0.82),
             "green": (0.10, 0.62, 0.22), "yellow": (0.96, 0.80, 0.08)}


def px(x, y):
    return (x - X0) / RES, (Y1 - y) / RES


def coverable_floor(models):
    """Floor cells the robot can sweep, reachable from its start pose."""
    W, H = int((X1 - X0) / RES), int((Y1 - Y0) / RES)
    sdf = (models / "house_int2" / "model.sdf").read_text()
    items = [("house_int2", [0.0] * 6)] + [
        (uri, [float(v) for v in pose.split()])
        for uri, pose in re.findall(r"<uri>model://(\w+)</uri>\s*<pose>([^<]+)</pose>", sdf)
    ]

    img = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(img)
    for name, (x, y, z, roll, pitch, yaw) in items:
        mesh = trimesh.load(models / name / "meshes" / "model.dae", force="scene").to_geometry()
        mesh.apply_transform(trimesh.transformations.compose_matrix(
            angles=[roll, pitch, yaw], translate=[x, y, z]))
        tri = mesh.triangles
        zmin, zmax = tri[:, :, 2].min(1), tri[:, :, 2].max(1)
        # Triangles crossing the robot height band, walls show up as lines
        for t in tri[(zmax > 0.015) & (zmin < ROBOT_HEIGHT)]:
            draw.polygon([px(*v[:2]) for v in t], fill=255, outline=255)
    for _, _, can, _ in PAINTS:
        cx, cy = px(*can)
        r = CAN_FOOTPRINT / RES
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=255)

    obstacles = np.array(img) > 0
    k = int(ROBOT_RADIUS / RES)
    yy, xx = np.mgrid[-k:k + 1, -k:k + 1]
    disk = xx ** 2 + yy ** 2 <= k * k
    labels, _ = ndimage.label(~ndimage.binary_dilation(obstacles, disk))
    sx, sy = px(*ROBOT_START)
    reachable = labels == labels[int(sy), int(sx)]
    return ndimage.binary_dilation(reachable, disk) & ~obstacles


def write_cans(models_dir):
    """Lying paint can, open end along +x, one model per paint color."""
    for name, _, _, _ in PAINTS:
        r, g, b = PAINT_RGB[name]
        d = models_dir / f"paint_can_{name}"
        d.mkdir(parents=True, exist_ok=True)
        (d / "model.config").write_text(f"""<?xml version="1.0"?>
<model>
  <name>paint_can_{name}</name>
  <version>1.0</version>
  <sdf version="1.8">model.sdf</sdf>
  <description>Knocked over can of {name} paint, generated by generate_party_house.py</description>
</model>
""")
        metal = "<ambient>0.55 0.56 0.58 1</ambient><diffuse>0.70 0.71 0.73 1</diffuse><specular>0.6 0.6 0.6 1</specular>"
        paint = f"<ambient>{r * 0.8:.2f} {g * 0.8:.2f} {b * 0.8:.2f} 1</ambient><diffuse>{r:.2f} {g:.2f} {b:.2f} 1</diffuse><specular>0.3 0.3 0.3 1</specular>"
        half = CAN_LENGTH / 2
        (d / "model.sdf").write_text(f"""<?xml version="1.0"?>
<sdf version="1.8">
  <model name="paint_can_{name}">
    <static>true</static>
    <link name="link">
      <collision name="can">
        <pose>0 0 {CAN_RADIUS} 0 1.5708 0</pose>
        <geometry><cylinder><radius>{CAN_RADIUS}</radius><length>{CAN_LENGTH}</length></cylinder></geometry>
      </collision>
      <visual name="can">
        <pose>0 0 {CAN_RADIUS} 0 1.5708 0</pose>
        <geometry><cylinder><radius>{CAN_RADIUS}</radius><length>{CAN_LENGTH}</length></cylinder></geometry>
        <material>{metal}</material>
      </visual>
      <visual name="label">
        <pose>-0.01 0 {CAN_RADIUS} 0 1.5708 0</pose>
        <geometry><cylinder><radius>{CAN_RADIUS + 0.002}</radius><length>{CAN_LENGTH * 0.55}</length></cylinder></geometry>
        <material>{paint}</material>
      </visual>
      <visual name="paint">
        <pose>{half + 0.001} 0 {CAN_RADIUS} 0 1.5708 0</pose>
        <geometry><cylinder><radius>{CAN_RADIUS - 0.006}</radius><length>0.002</length></cylinder></geometry>
        <material>{paint}</material>
      </visual>
    </link>
  </model>
</sdf>
""")


def main():
    models = Path(sys.argv[1]) / "roomba_robot" / "models"
    out = Path(sys.argv[2])
    rng = np.random.default_rng(SEED)
    cover = coverable_floor(models)
    H, W = cover.shape

    def free(x, y):
        c, r = int((x - X0) / RES), int((Y1 - y) / RES)
        return 0 <= r < H and 0 <= c < W and cover[r, c]

    def density(x, y):
        return BASE_DENSITY + sum(
            w * math.exp(-((x - hx) ** 2 + (y - hy) ** 2) / (2 * s * s)) for hx, hy, s, w in HOTSPOTS)

    def random_point():
        return rng.uniform(X0, X1), rng.uniform(Y0, Y1)

    dmax = BASE_DENSITY + sum(h[3] for h in HOTSPOTS)
    points = []
    while len(points) < CONFETTI * 0.8:
        x, y = random_point()
        if free(x, y) and rng.uniform() < density(x, y) / dmax:
            points.append((x, y))
    # Small clumps, the kind that piles up by walls and furniture
    while len(points) < CONFETTI:
        x, y = random_point()
        if not free(x, y) or rng.uniform() > density(x, y) / dmax + 0.15:
            continue
        s = rng.uniform(0.05, 0.18)
        for _ in range(rng.integers(15, 50)):
            cx, cy = x + rng.normal(0, s), y + rng.normal(0, s)
            if free(cx, cy):
                points.append((cx, cy))

    lines = []
    for x, y in points:
        color = int(rng.integers(N_COLORS)) * N_SHADES + int(rng.integers(N_SHADES))
        yaw = rng.uniform(0, 2 * math.pi)
        kind = rng.uniform()
        if kind < 0.55:
            lines.append(f"confetti rect {x:.4f} {y:.4f} {yaw:.3f} "
                         f"{rng.uniform(0.015, 0.026):.4f} {rng.uniform(0.010, 0.020):.4f} {color}")
        elif kind < 0.92:
            d = rng.uniform(0.014, 0.024)
            lines.append(f"confetti disc {x:.4f} {y:.4f} 0 {d:.4f} {d:.4f} {color}")
        else:
            # Curly streamer as a few bent segments
            seg = rng.uniform(0.03, 0.05)
            cx, cy, a = x, y, yaw
            for _ in range(rng.integers(2, 5)):
                mx, my = cx + math.cos(a) * seg / 2, cy + math.sin(a) * seg / 2
                if free(mx, my):
                    lines.append(f"confetti rect {mx:.4f} {my:.4f} {a:.3f} {seg:.4f} 0.0045 {color}")
                cx, cy = cx + math.cos(a) * seg, cy + math.sin(a) * seg
                a += rng.normal(0, 0.9)

    # Paint puddles, a blob of overlapping drops from the can mouth onwards
    for _, color, can, spot in PAINTS:
        drops = 0
        while drops < PUDDLE_DROPS:
            t = rng.uniform(0.0, 1.15)
            x = can[0] + (spot[0] - can[0]) * t + rng.normal(0, 0.05)
            y = can[1] + (spot[1] - can[1]) * t + rng.normal(0, 0.05)
            if not free(x, y):
                continue
            d = rng.uniform(0.03, 0.07) * (1.2 - 0.5 * t)
            lines.append(f"paint disc {x:.4f} {y:.4f} 0 {d:.4f} {d:.4f} {color + int(rng.integers(2))}")
            drops += 1

    out.mkdir(parents=True, exist_ok=True)
    with open(out / "pieces.txt", "w") as f:
        f.write("# category shape x y yaw size_x size_y color\n")
        f.write("\n".join(lines) + "\n")

    # The cat keeps off the walls but always walks where the robot can clean
    k = int(CAT_CLEARANCE / RES)
    yy, xx = np.mgrid[-k:k + 1, -k:k + 1]
    walk = ndimage.binary_erosion(cover, xx ** 2 + yy ** 2 <= k * k)
    step = int(round(CAT_MAP_RES / RES))
    hh, ww = (H // step) * step, (W // step) * step
    coarse = walk[:hh, :ww].reshape(hh // step, step, ww // step, step).all(axis=(1, 3))
    # Keep only the area connected to the puddles so every goal is reachable
    def cell(p):
        return int((Y1 - p[1]) / CAT_MAP_RES), int((p[0] - X0) / CAT_MAP_RES)
    labels, _ = ndimage.label(coarse)
    first = labels[cell(PAINTS[0][3])]
    for name, _, _, spot in PAINTS:
        assert labels[cell(spot)] == first and first > 0, f"the cat must reach the {name} puddle"
    coarse = labels == first
    write_cans(out.parent)
    Image.fromarray(np.where(coarse, 0, 255).astype(np.uint8)).save(out / "cat_map.pgm")
    print(f"pieces {len(lines)}  cat map origin_x {X0} origin_y {Y1 - coarse.shape[0] * CAT_MAP_RES:.2f}")


if __name__ == "__main__":
    main()
