<?xml version="1.0"?>
<package format="3">

  <name>gz_mimic_joint</name>
  <version>0.0.1</version>

  <description>Gazebo Harmonic Mimic Joint Plugin</description>

  <maintainer email="dev@todo.com">dev</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>gz-sim8</depend>
  <depend>gz-plugin2</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>