<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>common_interfaces_cpp</name>
  <version>0.0.0</version>
  <description>C++ shared library providing ROS 2 interfaces for hardware components.</description>
  <maintainer email="dummy@dummy.com">dummy</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>cv_bridge</depend>
  <depend>opencv</depend>

  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>gazebo_msgs</depend>
  <depend>rosgraph_msgs</depend>
  <depend>ros_gz_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>