--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: robot_viewer; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.robot_viewer (
    id integer NOT NULL,
    name text NOT NULL,
    folder_path text NOT NULL
);


ALTER TABLE public.robot_viewer OWNER TO "user-dev";

--
-- Name: robot_viewer_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.robot_viewer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.robot_viewer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_viewer; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.world_viewer (
    id integer NOT NULL,
    name text NOT NULL,
    folder_path text NOT NULL
);


ALTER TABLE public.world_viewer OWNER TO "user-dev";

--
-- Name: world_viewer_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.world_viewer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_viewer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: robot_viewer; Type: TABLE DATA; Schema: public; Owner: user-dev
--

COPY public.robot_viewer (id, name, folder_path) FROM stdin;
1	Turtlebot 2	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/Turtlebot2/turtlebot2_simulated/turtlebot2/urdf/turtlebot2.urdf
2	F1_astonMartin	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/f1/models/f1_astonMartin/f1Aston.urdf
3	F1_redBull	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/f1/models/f1_redBull/f1redbull.urdf
4	F1_renault	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/f1/models/f1_renault/f1renault.urdf
5	Lincoln	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/ackermann_cars/models/lincoln/lincoln.urdf
6	Prius	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/taxi_navigator/models/prius/urdf/prius.urdf
7	Amazon Robot	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/amazon_robot/urdf/amazon_robot.urdf
8	Turtlebot3	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/turtlebot3/urdf/turtlebot3_waffle.urdf
9	Typhoon h480 dual cam	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/drone_assets/models/typhoon_h480_dual_cam/typhoon.urdf
10	Ackermann Logistic Robot	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/ackermann_logistic_robot/models/ackermann_logistic_robot/ackermannLogisticRobot.urdf
11	Roomba	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/roomba_robot/models/roombaROS/roomba.glb
\.

--2	Roomba	../../../../static/RoboticsAcademy/RoboticsInfrastructure/CustomRobots/roomba_robot/models/roombaROS/roombaROS.urdf

--
-- Data for Name: world_viewer; Type: TABLE DATA; Schema: public; Owner: user-dev
--

COPY public.world_viewer (id, name, folder_path) FROM stdin;
1	3D Reconstruction	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/3DReconstruction.glb
2	Autoparking Simple: In Line	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/ASimpleInLine.glb
3	City Large	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/CityLarge.glb
4	Follow Person	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/Hospital.glb
5	Laser Mapping Warehouse	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/LaserMappingWarehouse.glb
6	Montmelo Ackermann Circuit	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/Montmelo.glb
7	Montreal Circuit	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/Montreal.glb
8	Nurburgring Circuit	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/Nurburgring.glb
9	Restaurant	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/Restaurant.glb
10	Simple Circuit	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/SimpleCircuit.glb
11	Vacuums House	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/VacuumsHouse.glb
12	Vacuums House Markers	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/LakeHouse.glb
13	Warehouse 1	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/AmazonWarehouse.glb
14	Rescue People Harmonic	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/RescuePeople.glb
15	Follow Road Harmonic	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/FollowRoad.glb
16	Pick & Place Arm	../../../../static/RoboticsAcademy/RoboticsInfrastructure/Worlds/SmallLaserWarehouse.glb
\.


--
-- Name: robot_viewer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval('public.robot_viewer_id_seq', 11, true);


--
-- Name: world_viewer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval('public.world_viewer_id_seq', 16, true);


--
-- Name: robot_viewer robot_viewer_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.robot_viewer
    ADD CONSTRAINT robot_viewer_pkey PRIMARY KEY (id);


--
-- Name: world_viewer world_viewer_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.world_viewer
    ADD CONSTRAINT world_viewer_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

