--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: robot_viewer; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.robot_viewer (
    id integer NOT NULL,
    name text NOT NULL,
    folder_path text NOT NULL
);


ALTER TABLE public.robot_viewer OWNER TO "user-dev";

--
-- Name: robot_viewer_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.robot_viewer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.robot_viewer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_viewer; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.world_viewer (
    id integer NOT NULL,
    name text NOT NULL,
    folder_path text NOT NULL
);


ALTER TABLE public.world_viewer OWNER TO "user-dev";

--
-- Name: world_viewer_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.world_viewer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_viewer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: robot_viewer; Type: TABLE DATA; Schema: public; Owner: user-dev
--

COPY public.robot_viewer (id, name, folder_path) FROM stdin;
2	Roomba	ViewerModels/Robots/Roomba.glb
3	F1_astonMartin	ViewerModels/Robots/F1_astonMartin.glb
4	F1_redBull	ViewerModels/Robots/F1_redBull.glb
5	F1_renault	ViewerModels/Robots/F1_renault.glb
6	Lincoln	ViewerModels/Robots/Lincoln.glb
7	Prius	ViewerModels/Robots/Prius.glb
8	Amazon Robot	ViewerModels/Robots/AmazonRobot.glb
9	Turtlebot3	ViewerModels/Robots/Turtlebot3.glb
10	Quadrotor Dual Cam	ViewerModels/Robots/Quadrotor.glb
1	Turtlebot 2	ViewerModels/Robots/Turtlebot2.glb
11	Ackermann Logistic Robot	ViewerModels/Robots/AckermannLogistic.glb
\.


--
-- Data for Name: world_viewer; Type: TABLE DATA; Schema: public; Owner: user-dev
--

COPY public.world_viewer (id, name, folder_path) FROM stdin;
1	3D Reconstruction	ViewerModels/Worlds/3DReconstruction.glb
2	Autoparking Simple: In Line	ViewerModels/Worlds/ASimpleInLine.glb
3	City Large	ViewerModels/Worlds/CityLarge.glb
4	Follow Person	ViewerModels/Worlds/Hospital.glb
5	Laser Mapping Warehouse	ViewerModels/Worlds/LaserMappingWarehouse.glb
6	Montmelo Ackermann Circuit	ViewerModels/Worlds/Montmelo.glb
7	Montreal Circuit	ViewerModels/Worlds/Montreal.glb
8	Nurburgring Circuit	ViewerModels/Worlds/Nurburgring.glb
9	Restaurant	ViewerModels/Worlds/Restaurant.glb
10	Simple Circuit	ViewerModels/Worlds/SimpleCircuit.glb
11	Vacuums House	ViewerModels/Worlds/VacuumsHouse.glb
12	Vacuums House Markers	ViewerModels/Worlds/LakeHouse.glb
13	Warehouse 1	ViewerModels/Worlds/AmazonWarehouse.glb
14	Rescue People Harmonic	ViewerModels/Worlds/RescuePeople.glb
15	Follow Road Harmonic	ViewerModels/Worlds/FollowRoad.glb
16	Pick & Place Arm	ViewerModels/Worlds/SmallLaserWarehouse.glb
\.


--
-- Name: robot_viewer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval('public.robot_viewer_id_seq', 11, true);


--
-- Name: world_viewer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval('public.world_viewer_id_seq', 16, true);


--
-- Name: robot_viewer robot_viewer_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.robot_viewer
    ADD CONSTRAINT robot_viewer_pkey PRIMARY KEY (id);


--
-- Name: world_viewer world_viewer_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.world_viewer
    ADD CONSTRAINT world_viewer_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

