--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: robot_viewer; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.robot_viewer (
    id integer NOT NULL,
    name text NOT NULL,
    folder_path text NOT NULL
);


ALTER TABLE public.robot_viewer OWNER TO "user-dev";

--
-- Name: robot_viewer_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.robot_viewer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.robot_viewer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: world_viewer; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.world_viewer (
    id integer NOT NULL,
    name text NOT NULL,
    folder_path text NOT NULL
);


ALTER TABLE public.world_viewer OWNER TO "user-dev";

--
-- Name: world_viewer_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.world_viewer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.world_viewer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: robot_viewer; Type: TABLE DATA; Schema: public; Owner: user-dev
--

COPY public.robot_viewer (id, name, folder_path) FROM stdin;
1	Turtlebot 2	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/Turtlebot2/turtlebot2_simulated/turtlebot2/urdf/turtlebot2.urdf
3	F1_redBull	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/f1/models/f1_redBull/f1redbull.urdf
5	Lincoln	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/ackermann_cars/models/lincoln/lincoln.urdf
6	Prius	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/taxi_navigator/models/prius/urdf/prius.urdf
7	Amazon Robot	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/amazon_robot/urdf/amazon_robot.urdf
8	Turtlebot3	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/turtlebot3/urdf/turtlebot3_waffle.urdf
9	Typhoon h480 dual cam	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/drone_assets/models/typhoon_h480_dual_cam/typhoon.urdf
2	F1_astonMartin	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/f1/models/f1_astonMartin/f1Aston.urdf
4	F1_renault	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/f1/models/f1_renault/f1renault.urdf
10	Ackermann Logistic Robot	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/ackermann_logistic_robot/models/ackermann_logistic_robot/ackermannLogisticRobot.urdf
11	Roomba	../../../../static/ModelsViewer/RoboticsInfrastructure/CustomRobots/roomba_robot/models/roombaROS/roombaROS.urdf
\.


--
-- Data for Name: world_viewer; Type: TABLE DATA; Schema: public; Owner: user-dev
--

COPY public.world_viewer (id, name, folder_path) FROM stdin;
1	AutoPark Lincoln1	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/autoparking_lincoln_1laser.urdf
2	AutoPark Lincoln3	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/autoparking_lincoln_3laser.urdf
3	AutoPark Prius1	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/autoparking_prius_1laser.urdf
4	AutoPark Prius3	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/autoparking_prius_3laser.urdf
5	Autopark Battery	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/autopark_battery.urdf
6	Autopark Line	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/autopark_line.urdf
7	Autopark Line Lidar	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/autopark_line_lidar.urdf
8	Autopark Side	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/autopark_sideways.urdf
9	Battery Lincoln1	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/bateria_lincoln_1laser.urdf
10	Battery Lincoln3	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/bateria_lincoln_3laser.urdf
11	Battery Prius3	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/bateria_prius_3laser.urdf
12	Gas Battery	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/gas_station_battery.urdf
13	Gas Battery Ack	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/gas_station_battery_ackermann.urdf
14	Gas Line	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/gas_station_line.urdf
15	Gas Line Ack	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/gas_station_line_ackermann.urdf
16	Gas station Park	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/gas_station_parking.urdf
17	Gas Park Ack	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/gas_station_parking_ackermann.urdf
18	Hospital FP	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/hospital_follow_person.urdf
19	Hospital FP Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/hospital_follow_person_followingcam.urdf
20	Hospital Teleop	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/hospital_follow_person_teleop.urdf
21	3D Reconstruction	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/kobuki_3d_reconstruction.urdf
22	Laser Map	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/laser_map.urdf
23	Marker Visual Loc	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/marker_visual_loc.urdf
24	Monaco	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/monaco_circuit.urdf
25	Montmelo	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/montmelo_line.urdf
26	Montmelo Ack	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/montmelo_line_ackermann.urdf
27	Montmelo Ack Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/montmelo_line_ackermann_followingcam.urdf
28	Montmelo Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/montmelo_line_followingcam.urdf
29	Montreal	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/montreal_line.urdf
30	Montreal Ack	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/montreal_line_ackermann.urdf
31	Montreal Ack Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/montreal_line_ackermann_followingcam.urdf
32	Montreal Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/montreal_line_followingcam.urdf
33	Small Warehouse Ack Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/no_roof_small_warehouse_with_ackermann_logistic_robot_followingcam.urdf
34	Small Warehouse Bot	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/no_roof_small_warehouse_with_robot.urdf
35	Small Warehouse Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/no_roof_small_warehouse_with_robot_followingcam.urdf
36	Nurburgring	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/nurburgring_line.urdf
37	Nurburgring Ack	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/nurburgring_line_ackermann.urdf
38	Nurburgring Ack Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/nurburgring_line_ackermann_followingcam.urdf
39	Nurburgring Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/nurburgring_line_followingcam.urdf
40	Obstacle avoidance	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/obstacle_avoidance_h.urdf
41	Pallet warehouse Ack	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/pallet_warehouse_ackermann_logistic_robot.urdf
42	Pallet warehouse Bot	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/pallet_warehouse_with_robot.urdf
43	Pallet warehouse Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/pallet_warehouse_with_robot_followingcam.urdf
44	Rescue people	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/rescue_people.urdf
45	Restaurant	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/restaurant.urdf
46	Road junction	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/road_junction.urdf
47	Roomba house	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/roomba_1_house.urdf
48	Roomba house Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/roomba_1_house_followingcam.urdf
49	Roomba house Loc	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/roomba_1_house_followingcam_visual_loc.urdf
50	Simple circuit	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/simple_circuit.urdf
51	Simple circuit Ack	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/simple_circuit_ackermann.urdf
52	Simple circuit Ack Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/simple_circuit_ackermann_followingcam.urdf
53	Simple circuit Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/simple_circuit_followingcam.urdf
54	Simple circuit Obst	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/simple_circuit_obstacles.urdf
55	Small laser Map	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/small_laser_mapping.urdf
56	Spa	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/spa_circuit.urdf
57	Taxi City large	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/taxi_navigation_city_large.urdf
58	Taxi City large Cam	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/taxi_navigation_city_large_followingcam.urdf
59	Warehouse Arm	../../../../static/ModelsViewer/RoboticsInfrastructure/Universes/warehouse_arm.urdf
\.


--
-- Name: robot_viewer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval('public.robot_viewer_id_seq', 11, true);


--
-- Name: world_viewer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval('public.world_viewer_id_seq', 16, true);


--
-- Name: robot_viewer robot_viewer_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.robot_viewer
    ADD CONSTRAINT robot_viewer_pkey PRIMARY KEY (id);


--
-- Name: world_viewer world_viewer_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.world_viewer
    ADD CONSTRAINT world_viewer_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

