--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET transaction_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SELECT pg_catalog.set_config ('search_path', '', false);

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: worlds; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.worlds (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    scene_id bigint NOT NULL
);

ALTER TABLE public.worlds OWNER TO "user-dev";

--
-- Name: exercises_scene_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.worlds
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_scene_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: worlds_robots; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.worlds_robots (
    id bigint NOT NULL,
    world_id bigint NOT NULL,
    robot_id bigint NOT NULL,
    instances SMALLINT NOT NULL
);

ALTER TABLE public.worlds_robots OWNER TO "user-dev";

--
-- Name: worlds_robots_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.worlds_robots
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.worlds_robots_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: scenes; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.scenes (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    launch_file_path character varying(200) NOT NULL,
    tools_config character varying(200) NOT NULL,
    ros_version character varying(4) NOT NULL,
    type character varying(50) NOT NULL,
    start_pose real[] [6] NOT NULL
);

--
-- start_pose is '{X,Y,Z,Roll,Pitch,Yaw}'
--

ALTER TABLE public.scenes OWNER TO "user-dev";

--
-- Name: scenes_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.scenes
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scenes_id_seq START
    WITH
        0 INCREMENT BY 1 MINVALUE 0 NO MAXVALUE CACHE 1
);

--
-- Name: robots; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.robots (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    launch_file_path character varying(200) NOT NULL,
    entity character varying(32) NOT NULL,
    extra_config character varying(256) NOT NULL
);

ALTER TABLE public.robots OWNER TO "user-dev";

--
-- Name: robots_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.robots
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.robots_id_seq START
    WITH
        0 INCREMENT BY 1 MINVALUE 0 NO MAXVALUE CACHE 1
);

--
-- Name: tools; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.tools (
    name character varying(50) NOT NULL PRIMARY KEY,
    base_config character varying(200) NOT NULL
);

ALTER TABLE public.tools OWNER TO "user-dev";

--
-- Data for Name: worlds; Type: TABLE DATA; Schema: public; Owner: user-dev
--


COPY public.worlds (id, name, scene_id) FROM stdin;
1	Vacuums House	24
5	Simple Circuit	23
6	Montreal Circuit	16
11 	City Large	9
12 	3d Reconstruction	46
20 	Montmelo Circuit	14
21 	Nurburgring Circuit	18
22 	Nurburgring Ackermann Circuit	18
23 	Montmelo Ackermann Circuit	14
24 	Montreal Ackermann Circuit	16
25 	Simple Ackermann Circuit	23
27	Vacuums House Roof	26
29	Vacuums House Markers	25
30	Small Laser Mapping Warehouse	33
31	Rescue People	31
32	Follow Road	32
33	Laser Mapping Warehouse Low Noise	12
35	Car Junction World	35
36	Drone Gymkhana World	36
37	Tower Inspection World	37
39	Labyrinth Escape World	39
40	Obstacle Avoidance	40
41	Autopark_line	41
42	Autopark_battery	42
43	Autopark_sideways	43
44	Autopark Lidar Line	41
47	Spa Circuit	47
48 	Monaco Ackermann Circuit	49
49 	Monaco Circuit	49
55 	Rover 4wd Warehouse	55
56	Pick And Place World	56
57 	Package delivery	57
58	Warehouse 1	58
59	Warehouse 2	59
60	Warehouse 1 Ackermann	58
61	Warehouse 2 Ackermann	59
62	Laser Mapping Warehouse Medium Noise	12
63	Laser Mapping Warehouse High Noise	12
64	Small Laser Mapping Warehouse Medium Noise	33
65	Small Laser Mapping Warehouse High Noise	33
66	Follow Person	66
67	Follow Person Teleop	67
68	Rover 4wd Warehouse Low Noise	68
69	Rover 4wd Warehouse High Noise	68
70	Machine vision world	70
71	Conveyor Belt World	71
72	Drone Cat Mouse	72
\.

--
-- Data for Name: worlds_robots; Type: TABLE DATA; Schema: public; Owner: user-dev
--


COPY public.worlds_robots (id, world_id, robot_id, instances) FROM stdin; 
0	1	9	1
1	5	2	1
2	6	2	1
3	11 	18	1
4	12 	16	1
5	20 	2	1
6	21 	2	1
7	22 	4	1
8	23 	4	1
9	24 	4	1
10	25 	4	1
11	27	10	1
12	29	21	1
13	30	28	1
14	31	11	1
15	32	11	1
16	33	28	1
17	35	6	1
18	36	11	1
19	37	11	1
20	39	11	1
21	40	3	1
22	41	8	1
23	42	8	1
24	43	8	1
25	44	7	1
26	47	2	1
27	48 	4	1
28	49 	2	1
29	55 	12	1
30	56	1	1
31	57 	11	1
32	58	13	1
33	59	13	1
34	60	14	1
35	61	14	1
36	62	29	1
37	63	30	1
38	64	29	1
39	65	30	1
40	66	15	1
41	67	15	1
42	68	19	1
43	69	20	1
44	70	24	1
45	71	26	1
46	72	11	2
\.

--
-- Data for Name: scenes; Type: TABLE DATA; Schema: public; Owner: user-dev
--


COPY public.scenes (id, name, launch_file_path, tools_config, ros_version, type, start_pose) FROM stdin;
9	City Large	/opt/jderobot/Launchers/basic_city.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/basic_city.config"}	ROS2	gz	{{0,0,0.1,0,0,-1.5529944}}
12	Laser Mapping Warehouse	/opt/jderobot/Launchers/laser_mapping.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/laser_mapping.config"}	ROS2	gz	{{14.25,-10.75,0.1,0,-0,3.14}}
14	Montmelo Circuit	/opt/jderobot/Launchers/montmelo_circuit.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/montmelo_circuit.config"}	ROS2	gz	{{27.18, -31.55, 0.0, 0.0, 0.01, -3.12}}
16	Montreal Circuit	/opt/jderobot/Launchers/montreal_circuit.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/montreal_circuit.config"}	ROS2	gz	{{-200.88, -90.72, 0.0, 0.0, 0.0, -2.83}}
18	Nurburgring Circuit	/opt/jderobot/Launchers/nurburgring_circuit.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/nurburgring_circuit.config"}	ROS2	gz	{{-74.29, 37.74, 0.0, 0.0, 0.0, -0.51}}
23	Simple Circuit	/opt/jderobot/Launchers/simple_circuit.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/simple_circuit.config"}	ROS2	gz	{{53.462,-10.734,0.004,0,0,-1.57}}
24	Small House	/opt/jderobot/Launchers/small_house.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/small_house.config"}	ROS2	gz	{{-1,1.5,0,0.0,0.0,0.0}}
25	Vacuums House Markers	/opt/jderobot/Launchers/detailed_house.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/detailed_house.config"}	ROS2	gz	{{1,-1.5,0.43,0,0,0}}
26	Small House Roof	/opt/jderobot/Launchers/small_house_roof.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/small_house_roof.config"}	ROS2	gz	{{-1,1.5,0.0,0.0,0.0,0.0}}
31	Rescue People	/opt/jderobot/Launchers/rescue_people.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/rescue_people.config"}	ROS2	gz	{{0.0,0.0,1.45,0.0,0.0,0.0}}
32	Follow Road	/opt/jderobot/Launchers/follow_road.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/follow_road.config"}	ROS2	gz	{{17.96,0.0,0.3,0,0,-2.0}}
33	Small Laser Mapping Warehouse	/opt/jderobot/Launchers/small_laser_mapping.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/small_laser_mapping.config"}	ROS2	gz	{{0.0,0.0,0.0,0.0,0.0,0.0}}
35	Car Junction	/opt/jderobot/Launchers/car_junction.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/car_junction.config"}	ROS2	gz	{{2.5,-30,0.1,0,0,1.57}}
36	Drone Gymkhana	/opt/jderobot/Launchers/drone_gymkhana.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/drone_gymkhana.config"}	ROS2	gz	{{0.0,0.0,1.05,0.0,0.0,0.0}}
37	Tower Inspection	/opt/jderobot/Launchers/power_tower_inspection.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/power_tower_inspection.config"}	ROS2	gz	{{-21.0,-4.0,0.15,0,0,0}}
39	Labyrinth Escape	/opt/jderobot/Launchers/labyrinth_escape.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/labyrinth_escape.config"}	ROS2	gz	{{-18,-8.5,0.3,0,0,0}}
40	Obstacle Avoidance	/opt/jderobot/Launchers/obstacle_avoidance_h.launch.py	None	ROS2	gz	{{0.04,0.68,0,0,0,-1.57}}
41	Autopark_line	/opt/jderobot/Launchers/autopark_line.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/autoparking.config"}	ROS2	gz	{{-7,2.5,0.004,0.0,0.0,0}}
42	Autopark_battery	/opt/jderobot/Launchers/autopark_battery.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/autoparking.config"}	ROS2	gz	{{-7,2.5,0.004,0.0,0.0,0}}
43	Autopark_sideways	/opt/jderobot/Launchers/autopark_sideways.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/autoparking.config"}	ROS2	gz	{{-7,2.5,0.004,0.0,0.0,0}}
46	3d Reconstruction	/opt/jderobot/Launchers/3d_reconstruction.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/3d_reconstruction.config"}	ROS2	gz	{{0.0,0.0,0.0,0.0,0.0,0.0}}
47	Spa Circuit	/opt/jderobot/Launchers/spa_circuit.launch.py	None	ROS2	gz	{{146,60,-593.20,0,0,0.35}}
49	Monaco Circuit	/opt/jderobot/Launchers/monaco_circuit.launch.py	None	ROS2	gz	{{-105.223, -70.77, -1.8, 0.0, 0.0, 1.69}}
55	Rover 4wd Warehouse	/opt/jderobot/Launchers/rover_4wd_warehouse.launch.py	None	ROS2	gz	{{0.0,0.0,0.15,0.0,0.0,0.0}}
56	Pick And Place	/opt/jderobot/Launchers/pick_place.launch.py	{"rviz":"/opt/jderobot/Launchers/rviz/pick_place_harmonic.launch.py"}	ROS2	gz	{{0.0,0.0,0.9,0.0,0.0,0.0}}
57	Package delivery	/opt/jderobot/Launchers/package_delivery.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/package_delivery.config"}	ROS2	gz	{{-1.0,-4.0,0.3,0,0,1.5729}}
58	Warehouse 1	/opt/jderobot/Launchers/warehouse1.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/amazon_robot_harmonic.config"}	ROS2	gz	{{0.0,0.0,0.1,0.0,0.0,0.0}}
59	Warehouse 2	/opt/jderobot/Launchers/warehouse2.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/amazon_robot_harmonic.config"}	ROS2	gz	{{0.0,0.0,0.1,0.0,0.0,0.0}}
66	Follow Person	/opt/jderobot/Launchers/follow_person_harmonic.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/follow_person.config"}	ROS2	gz	{{-1.0,10.0,0.1,0.0,0.0,0.0}}
67	Follow Person Teleop	/opt/jderobot/Launchers/follow_person_teleop_harmonic.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/follow_person.config"}	ROS2	gz	{{-1.0,10.0,0.1,0.0,0.0,0.0}}
68	Rover 4wd Warehouse Low Noise	/opt/jderobot/Launchers/rover_4wd_warehouse.launch.py	None	ROS2	gz	{{0.0,0.0,0.0,0.0,0.0,0.0}}
70	Machine Vision	/opt/jderobot/Launchers/machine_vision.launch.py	{"rviz":"/opt/jderobot/Launchers/rviz/pick_place_harmonic.launch.py"}	ROS2	gz	{{0.0,0.0,0.9,0.0,0.0,0.0}}
71	Conveyor	/opt/jderobot/Launchers/sausage_exercise.launch.py	{"rviz":"/opt/jderobot/Launchers/rviz/sausage_exercise.launch.py"}	ROS2	gz	{{-0.4,-0.5,0.8,0.0,0.0,0.0}}
72	Drone Cat Mouse	/opt/jderobot/Launchers/drone_cat_mouse.launch.py	{"gzsim":"/opt/jderobot/Launchers/visualization/drone_cat_mouse.config"}	ROS2	gz	{{0,5,0.2,0.0,0.0,0.0},{20,5,0.2,0.0,0.0,0.0}}
\.

--
-- Data for Name: robots; Type: TABLE DATA; Schema: public; Owner: user-dev
--


COPY public.robots (id, name, launch_file_path, entity, extra_config) FROM stdin;
1	Ur5	/home/ws/src/CustomRobots/robot_arms/launch/ur5.launch.py	ur5_robotiq	None
2	F1 Holonomic Camera	/home/ws/src/CustomRobots/f1/launch/f1.launch.py	f1	mode:=holo sensor:=camera namespace:=f1
3	F1 Holonomic Laser	/home/ws/src/CustomRobots/f1/launch/f1.launch.py	f1	mode:=holo sensor:=laser namespace:=f1
4	F1 Ackermann Camera	/home/ws/src/CustomRobots/f1/launch/f1.launch.py	f1	mode:=ackermann sensor:=camera namespace:=f1
5	F1 Ackermann Laser	/home/ws/src/CustomRobots/f1/launch/f1.launch.py	f1	mode:=ackermann sensor:=laser namespace:=f1
6	Autonomous car Camera	/home/ws/src/CustomRobots/autonomous_car/launch/autonomous_car.launch.py	autonomous_car	sensor:=camera namespace:=autonomous_car 
7	Autonomous car Lidar	/home/ws/src/CustomRobots/autonomous_car/launch/autonomous_car.launch.py	autonomous_car	sensor:=lidar namespace:=autonomous_car 
8	Autonomous car 3 Lasers	/home/ws/src/CustomRobots/autonomous_car/launch/autonomous_car.launch.py	autonomous_car	sensor:=laser namespace:=autonomous_car 
9	Vacuum cleaner Laser	/home/ws/src/CustomRobots/vacuum_cleaner/launch/vacuum_cleaner.launch.py	vacuum_cleaner	sensor:=laser namespace:=vacuum_cleaner 
10	Vacuum cleaner Camera	/home/ws/src/CustomRobots/vacuum_cleaner/launch/vacuum_cleaner.launch.py	vacuum_cleaner	sensor:=camera namespace:=vacuum_cleaner 
11	Quadrotor	/home/ws/src/CustomRobots/quadrotor/launch/quadrotor.launch.py	drone	sensor:=camera namespace:=drone
12	Rover 4wd	/home/ws/src/CustomRobots/rover_4wd/launch/rover_4wd.launch.py	rover_4wd	namespace:=rover_4wd
13	Holonomic Logistic	/home/ws/src/CustomRobots/logistic_holonomic_robot/launch/logistic_holonomic_robot.launch.py	logistic_holonomic_robot	namespace:=logistic_robot
14	Ackermann Logistic	/home/ws/src/CustomRobots/logistic_ackermann_robot/launch/logistic_ackermann_robot.launch.py	logistic_ackermann_robot	namespace:=logistic_robot
15	TurtleBot 2	/home/ws/src/CustomRobots/Turtlebot2/launch/turtlebot2.launch.py	turtlebot2	sensor:=camera namespace:=turtlebot2
16	TurtleBot 2 Stereo	/home/ws/src/CustomRobots/Turtlebot2/launch/turtlebot2.launch.py	turtlebot2	sensor:=stereo namespace:=turtlebot2
17	Turtlebot 3	/home/ws/src/CustomRobots/turtlebot3/launch/turtlebot3.launch.py	turtlebot3	namespace:=turtlebot3
18	Autonomous holonomic car	/home/ws/src/CustomRobots/autonomous_car/launch/autonomous_car.launch.py	autonomous_car	mode:=holonomic namespace:=autonomous_car
19	Rover 4wd Low Noise	/home/ws/src/CustomRobots/rover_4wd/launch/rover_4wd.launch.py	rover_4wd	noise:=low namespace:=rover_4wd
20	Rover 4wd High Noise	/home/ws/src/CustomRobots/rover_4wd/launch/rover_4wd.launch.py	rover_4wd	noise:=high namespace:=rover_4wd
21	Turtlebot 3 Low Noise	/home/ws/src/CustomRobots/turtlebot3/launch/turtlebot3.launch.py	turtlebot3	noise:=low namespace:=turtlebot3
22	Turtlebot 3 Medium Noise	/home/ws/src/CustomRobots/turtlebot3/launch/turtlebot3.launch.py	turtlebot3	noise:=med namespace:=turtlebot3
23	Turtlebot 3 High Noise	/home/ws/src/CustomRobots/turtlebot3/launch/turtlebot3.launch.py	turtlebot3	noise:=high namespace:=turtlebot3
24	Ur5 Camera	/home/ws/src/CustomRobots/robot_arms/launch/ur5.launch.py	ur5_robotiq	sensor:=camera
25	Ur3	/home/ws/src/CustomRobots/robot_arms/launch/ur3.launch.py	ur3_robotiq	None
26	Ur3 Camera	/home/ws/src/CustomRobots/robot_arms/launch/ur3.launch.py	ur3_robotiq	sensor:=camera
27	Dingo	/home/ws/src/CustomRobots/dingo/launch/dingo.launch.py	do150	namespace:=do150
28	Dingo Low Noise	/home/ws/src/CustomRobots/dingo/launch/dingo.launch.py	do150	noise:=low namespace:=do150
29	Dingo Medium Noise	/home/ws/src/CustomRobots/dingo/launch/dingo.launch.py	do150	noise:=med namespace:=do150
30	Dingo High Noise	/home/ws/src/CustomRobots/dingo/launch/dingo.launch.py	do150	noise:=high namespace:=do150
\.

--
-- Data for Name: tools; Type: TABLE DATA; Schema: public; Owner: user-dev
--


COPY public.tools (name, base_config) FROM stdin;
console	None
simulator	None
web_gui	None
state_monitor	None
webcam	None
rviz	None
video	None
\.

--
-- Name: exercises_scene_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval (
        'public.exercises_scene_id_seq', 1, false
    );

--
-- Name: scenes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval ( 'public.scenes_id_seq', 0, false );

--
-- Name: robots_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval ( 'public.robots_id_seq', 0, false );

--
-- Name: worlds_robots_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval (
        'public.worlds_robots_id_seq', 1, false
    );

--
-- Name: worlds exercises_worlds_name_key; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.worlds
ADD CONSTRAINT exercises_worlds_name_key UNIQUE (name);

--
-- Name: worlds worlds_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.worlds
ADD CONSTRAINT worlds_pkey PRIMARY KEY (id);

--
-- Name: exercises_world_name_459df99a_like; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX exercises_world_name_459df99a_like ON public.worlds USING btree (name varchar_pattern_ops);

--
-- PostgreSQL database dump complete
--

--
-- Name: worlds_robots worlds_robots_world_id_robot_id_155bee4e_uniq; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.worlds_robots
ADD CONSTRAINT worlds_robots_world_id_robot_id_155bee4e_uniq UNIQUE (world_id, robot_id);

--
-- Name: worlds_robots worlds_robots_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.worlds_robots
ADD CONSTRAINT worlds_robots_pkey PRIMARY KEY (id);

--
-- Name: worlds_robots_world_id_e4e984bc; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX worlds_robots_world_id_e4e984bc ON public.worlds_robots USING btree (world_id);

--
-- Name: worlds_robots_robot_id_13c30e27; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX worlds_robots_robot_id_13c30e27 ON public.worlds_robots USING btree (robot_id);

--
-- Name: worlds_robots worlds_robots_world_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.worlds_robots
ADD CONSTRAINT worlds_robots_world_id_fkey FOREIGN KEY (world_id) REFERENCES public.worlds (id);

--
-- Name: worlds_robots worlds_w_world_id_e4e984bc_fk_worlds; Type: FK CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.worlds_robots
ADD CONSTRAINT worlds_w_world_id_e4e984bc_fk_worlds FOREIGN KEY (world_id) REFERENCES public.worlds (id) DEFERRABLE INITIALLY DEFERRED;

--
-- PostgreSQL database dump complete
--