/**:
  ros__parameters:
    moveit_simple_controller_manager:
      controller_names:
        - arm_controller
        - gripper_controller

      arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - joint2_to_joint1
          - joint3_to_joint2
          - joint4_to_joint3
          - joint5_to_joint4
          - joint6_to_joint5
          - joint6output_to_joint6

      gripper_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - gripper_base_to_gripper_left3
