FROM jderobot/robotics-applications:pre-base

# Clone the RoboticsApplicationManager repository into the src folder inside RoboticsAcademy
RUN git clone https://github.com/JdeRobot/RoboticsApplicationManager.git /RoboticsApplicationManager