/**:
  ros__parameters:
    moveit_simple_controller_manager:
      controller_names:
        - left_arm_controller
        - right_arm_controller
        - left_gripper_controller
        - right_gripper_controller

      left_arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - Rotation_L
          - Pitch_L
          - Elbow_L
          - Wrist_Pitch_L
          - Wrist_Roll_L

      right_arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - Rotation_R
          - Pitch_R
          - Elbow_R
          - Wrist_Pitch_R
          - Wrist_Roll_R

      left_gripper_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - Jaw_L

      right_gripper_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - Jaw_R
