<?xml version="1.0"?>
<package format="3">
  <name>conveyor_belt_plugin</name>
  <version>0.0.0</version>
  <description>Conveyor belt plugin for Gazebo Harmonic</description>

  <maintainer email="you@todo.todo">you</maintainer>
  <license>TODO</license>

  <!-- Build -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies -->
  <depend>rclcpp</depend>
  <depend>gz-sim8</depend>
  <depend>gz-plugin2</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>